"""Build contrastive training pairs from Scryfall oracle tags (M6, step 1).

Produces the (anchor, positive) pairs that fine-tune the embedder, following
the recipe in ``docs/journal/2026-09-18-fine-tuning-pivot-oracle-tags-and-recipe.md``
§4a. This script covers the **tag-anchored** and **tag-description** anchor
sources; synthetic user queries (source 3) are generated by a separate script
because they need the LLM server and take hours.

Pair construction
-----------------
* **Tag pool** — a tag's card pool is its *closure* (the tag plus every
  descendant), which is exactly what Scryfall's ``otag:`` search returns
  (verified 2026-09-18). Tags with fewer than ``--min-cards`` in-corpus cards
  are skipped: too few positives to learn from and too few to hold out.
* **Anchors per tag** — the label, each alias, and the description when one
  exists. Each is a separate anchor string so the model learns the exact
  vocabulary the post-pivot rewriter will emit ("sweeper") *and* its player
  synonyms ("board wipe") *and* a short plain-language gloss.
* **Positives** — the card's Oracle text after the same reminder-text
  augmentation the corpus embedding uses (``build_embedding_text``), one
  face row at a time, so the positive side matches what Stage 3 indexes.
  Cards are sampled without replacement up to ``--max-per-anchor`` per
  anchor to stop the giant tags (``activated-ability``, 9k cards) from
  dominating the epoch.
* **Held-out tags** — ``--holdout-frac`` of eligible tags, stratified by
  pool-size bucket, are withheld entirely. Their pairs go to a separate
  probe file; the trainer must never see them. Retrieval on those tags
  after training is the jargon-generalisation probe.
* **Tag-aware batching support** — every pair carries its ``tag_id`` and
  the manifest records, per card, the full set of closure tags it belongs
  to, so the trainer can build batches in which no two anchors share a tag
  (the structural false-negative guard).

Prefixes are NOT applied here. The trainer applies ``search_query: `` /
``search_document: `` via Sentence Transformers ``prompts=`` so the pair
text stays encoder-agnostic, matching ``scripts/embed.py``.

Outputs (``data/training/``)::

    pairs_<version>.jsonl          training pairs (gitignored)
    holdout_<version>.jsonl        held-out tag pairs — probe only (gitignored)
    card_tags_<version>.json       oracle_id -> closure tag ids, for tag-aware batching (gitignored)
    manifest_<version>.json        counts, seed, held-out tag list (committed, small)

Usage::

    python scripts/build_training_pairs.py                  # version from --version, default v1
    python scripts/build_training_pairs.py --dry-run        # counts only
    python scripts/build_training_pairs.py --min-cards 10 --max-per-anchor 100
"""

from __future__ import annotations

import argparse
import json
import random
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import psycopg

from src.config import settings
from src.logging_utils import PipelineRun
from src.preprocess_text import build_embedding_text, load_keyword_dict

# Closure pool per tag, restricted to corpus cards. One row per (tag, card).
_POOL_SQL = """
    SELECT t.id::text, t.slug, t.label, t.description, t.aliases,
           ct.oracle_id::text
    FROM oracle_tags t
    JOIN oracle_tag_closure cl ON cl.ancestor_id = t.id
    JOIN card_tags ct          ON ct.tag_id = cl.descendant_id
    JOIN (SELECT DISTINCT oracle_id FROM cards) c ON c.oracle_id = ct.oracle_id
    GROUP BY t.id, t.slug, t.label, t.description, t.aliases, ct.oracle_id
"""

_FACES_SQL = """
    SELECT oracle_id::text, face_index, name, oracle_text, keywords
    FROM cards
    WHERE oracle_text <> ''
    ORDER BY oracle_id, face_index
"""

# Pool-size buckets for the stratified held-out split.
_BUCKETS = ((5, 20), (20, 100), (100, 500), (500, 10**9))


@dataclass
class Tag:
    id: str
    slug: str
    label: str
    description: str | None
    aliases: list[str]
    cards: list[str]  # oracle_ids in the closure pool, in corpus

    def anchors(self) -> list[tuple[str, str]]:
        """(kind, text) anchor strings for this tag."""
        out: list[tuple[str, str]] = [("label", self.label)]
        seen = {self.label.strip().lower()}
        for a in self.aliases:
            key = a.strip().lower()
            if key and key not in seen:
                seen.add(key)
                out.append(("alias", a.strip()))
        if self.description and self.description.strip():
            out.append(("description", self.description.strip()))
        return out


def _bucket(n: int) -> int:
    for i, (lo, hi) in enumerate(_BUCKETS):
        if lo <= n < hi:
            return i
    return len(_BUCKETS) - 1


def _load_tags(conn: psycopg.Connection, min_cards: int) -> list[Tag]:
    by_id: dict[str, Tag] = {}
    with conn.cursor() as cur:
        cur.execute(_POOL_SQL)
        for tag_id, slug, label, desc, aliases, oracle_id in cur:
            t = by_id.get(tag_id)
            if t is None:
                t = by_id[tag_id] = Tag(tag_id, slug, label, desc, list(aliases or []), [])
            t.cards.append(oracle_id)
    return sorted((t for t in by_id.values() if len(t.cards) >= min_cards), key=lambda t: t.slug)


def _load_faces(conn: psycopg.Connection) -> dict[str, list[tuple[int, str, str]]]:
    """oracle_id -> [(face_index, name, embedding_text)], reminder text applied."""
    keyword_dict = load_keyword_dict()
    faces: dict[str, list[tuple[int, str, str]]] = defaultdict(list)
    with conn.cursor() as cur:
        cur.execute(_FACES_SQL)
        for oracle_id, face_index, name, oracle_text, keywords in cur:
            text = build_embedding_text(oracle_text or "", keywords or [], keyword_dict)
            if text.strip():
                faces[oracle_id].append((face_index, name, text))
    return faces


def _split_holdout(tags: list[Tag], frac: float, rng: random.Random) -> set[str]:
    """Stratified-by-pool-size sample of tag ids to withhold."""
    by_bucket: dict[int, list[Tag]] = defaultdict(list)
    for t in tags:
        by_bucket[_bucket(len(t.cards))].append(t)
    held: set[str] = set()
    for bucket_tags in by_bucket.values():
        k = round(len(bucket_tags) * frac)
        held.update(t.id for t in rng.sample(bucket_tags, k))
    return held


def _emit_pairs(
    tag: Tag,
    faces: dict[str, list[tuple[int, str, str]]],
    max_per_anchor: int,
    rng: random.Random,
) -> list[dict[str, Any]]:
    pairs: list[dict[str, Any]] = []
    cards = [c for c in tag.cards if c in faces]
    for kind, anchor in tag.anchors():
        sample = cards if len(cards) <= max_per_anchor else rng.sample(cards, max_per_anchor)
        for oracle_id in sample:
            for face_index, name, text in faces[oracle_id]:
                pairs.append(
                    {
                        "anchor": anchor,
                        "positive": text,
                        "anchor_kind": kind,
                        "tag_id": tag.id,
                        "tag_slug": tag.slug,
                        "oracle_id": oracle_id,
                        "face_index": face_index,
                        "name": name,
                    }
                )
    return pairs


def main() -> int:
    sys.stdout.reconfigure(encoding="utf-8")
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--version", default="v1", help="Suffix for output files (default v1).")
    parser.add_argument(
        "--min-cards", type=int, default=5, help="Skip tags with fewer in-corpus cards."
    )
    parser.add_argument(
        "--max-per-anchor",
        type=int,
        default=150,
        help="Cap on cards sampled per anchor string (balances giant tags).",
    )
    parser.add_argument("--holdout-frac", type=float, default=0.15)
    parser.add_argument("--seed", type=int, default=20260918)
    parser.add_argument("--out-dir", type=Path, default=settings.training_dir)
    parser.add_argument("--dry-run", action="store_true", help="Compute counts, write nothing.")
    args = parser.parse_args()

    rng = random.Random(args.seed)
    args.out_dir.mkdir(parents=True, exist_ok=True)
    pairs_path = args.out_dir / f"pairs_{args.version}.jsonl"
    holdout_path = args.out_dir / f"holdout_{args.version}.jsonl"
    manifest_path = args.out_dir / f"manifest_{args.version}.json"
    card_tags_path = args.out_dir / f"card_tags_{args.version}.json"

    with PipelineRun(
        "build_training_pairs",
        inputs={
            "version": args.version,
            "min_cards": args.min_cards,
            "max_per_anchor": args.max_per_anchor,
            "holdout_frac": args.holdout_frac,
            "seed": args.seed,
            "preprocess_version": settings.preprocess_version,
            "dry_run": args.dry_run,
        },
    ) as run:
        with psycopg.connect(settings.database_url) as conn:
            tags = _load_tags(conn, args.min_cards)
            faces = _load_faces(conn)
            with conn.cursor() as cur:
                cur.execute("SELECT MAX(bulk_updated_at)::date::text FROM oracle_tags")
                bulk_date = cur.fetchone()[0]
        run.event("loaded", eligible_tags=len(tags), cards_with_text=len(faces))

        held = _split_holdout(tags, args.holdout_frac, rng)

        train_pairs: list[dict[str, Any]] = []
        holdout_pairs: list[dict[str, Any]] = []
        card_tags: dict[str, set[str]] = defaultdict(set)  # for tag-aware batching
        for t in tags:
            for c in t.cards:
                card_tags[c].add(t.id)
            target = holdout_pairs if t.id in held else train_pairs
            target.extend(_emit_pairs(t, faces, args.max_per_anchor, rng))
            run.processed()

        rng.shuffle(train_pairs)
        kinds = Counter(p["anchor_kind"] for p in train_pairs)
        train_tags = {p["tag_id"] for p in train_pairs}
        train_cards = {p["oracle_id"] for p in train_pairs}

        summary = {
            "version": args.version,
            "seed": args.seed,
            "tags_bulk_date": bulk_date,
            "preprocess_version": settings.preprocess_version,
            "min_cards": args.min_cards,
            "max_per_anchor": args.max_per_anchor,
            "holdout_frac": args.holdout_frac,
            "eligible_tags": len(tags),
            "train_tags": len(train_tags),
            "holdout_tags": len(held),
            "train_pairs": len(train_pairs),
            "holdout_pairs": len(holdout_pairs),
            "train_pairs_by_anchor_kind": dict(kinds),
            "train_cards": len(train_cards),
        }
        run.note(**summary)

        print()
        for k_, v in summary.items():
            print(f"  {k_:28s} {v}")
        if args.dry_run:
            print("  Dry run — nothing written.")
            return 0

        with pairs_path.open("w", encoding="utf-8") as fh:
            for p in train_pairs:
                fh.write(json.dumps(p, ensure_ascii=False) + "\n")
        with holdout_path.open("w", encoding="utf-8") as fh:
            for p in holdout_pairs:
                fh.write(json.dumps(p, ensure_ascii=False) + "\n")
        card_tags_path.write_text(
            json.dumps({c: sorted(ids) for c, ids in card_tags.items()}), encoding="utf-8"
        )
        manifest = {
            **summary,
            "holdout_tags": sorted(
                ({"id": t.id, "slug": t.slug, "cards": len(t.cards)} for t in tags if t.id in held),
                key=lambda d: d["slug"],
            ),
        }
        manifest_path.write_text(json.dumps(manifest, indent=1) + "\n", encoding="utf-8")
        run.note(
            pairs_path=str(pairs_path),
            holdout_path=str(holdout_path),
            card_tags_path=str(card_tags_path),
            manifest=str(manifest_path),
        )
        print(
            f"\n  Wrote {pairs_path.name}, {holdout_path.name}, "
            f"{card_tags_path.name}, {manifest_path.name}"
        )
        return 0


if __name__ == "__main__":
    sys.exit(main())
